
import { DateQuestion, CardTheme } from './types';

export const THEME_COLORS: Record<CardTheme, string> = {
  'Deep Conversation Starters': 'bg-indigo-100 text-indigo-700 border-indigo-200',
  'Fun & Silly Questions': 'bg-sky-100 text-sky-700 border-sky-200',
  'Dream Vacation Plans': 'bg-emerald-100 text-emerald-700 border-emerald-200',
  'Relationship Reflections': 'bg-rose-100 text-rose-700 border-rose-200'
};

const questions: Omit<DateQuestion, 'id'>[] = [
  // Deep Conversation Starters (25)
  { text: "What's a fear you've never told anyone about?", theme: 'Deep Conversation Starters' },
  { text: "What does 'home' mean to you?", theme: 'Deep Conversation Starters' },
  { text: "What's the most important lesson you've learned from a past mistake?", theme: 'Deep Conversation Starters' },
  { text: "If you could change one thing about your upbringing, what would it be?", theme: 'Deep Conversation Starters' },
  { text: "What are you most proud of in your life so far?", theme: 'Deep Conversation Starters' },
  { text: "What's your biggest 'what if'?", theme: 'Deep Conversation Starters' },
  { text: "How do you handle being vulnerable?", theme: 'Deep Conversation Starters' },
  { text: "What's the best piece of advice you've ever received?", theme: 'Deep Conversation Starters' },
  { text: "What do you want your legacy to be?", theme: 'Deep Conversation Starters' },
  { text: "What is your love language, and how can I speak it better?", theme: 'Deep Conversation Starters' },
  { text: "What makes you feel truly seen and understood?", theme: 'Deep Conversation Starters' },
  { text: "What's a habit you wish you could break?", theme: 'Deep Conversation Starters' },
  { text: "What does success look like to you in five years?", theme: 'Deep Conversation Starters' },
  { text: "If you could talk to your 10-year-old self, what would you say?", theme: 'Deep Conversation Starters' },
  { text: "What's something you've forgiven yourself for recently?", theme: 'Deep Conversation Starters' },
  { text: "What do you think is the key to a lifelong partnership?", theme: 'Deep Conversation Starters' },
  { text: "What is your favorite way to be comforted when you're sad?", theme: 'Deep Conversation Starters' },
  { text: "What's a dream you've given up on, and why?", theme: 'Deep Conversation Starters' },
  { text: "How has your definition of 'love' changed over time?", theme: 'Deep Conversation Starters' },
  { text: "What's the most courageous thing you've ever done?", theme: 'Deep Conversation Starters' },
  { text: "What's something you're currently struggling with that I can help with?", theme: 'Deep Conversation Starters' },
  { text: "Who has been the most influential person in your life?", theme: 'Deep Conversation Starters' },
  { text: "What is a boundary you've set that changed your life for the better?", theme: 'Deep Conversation Starters' },
  { text: "What does 'inner peace' look like for you?", theme: 'Deep Conversation Starters' },
  { text: "What's the most difficult choice you've ever had to make?", theme: 'Deep Conversation Starters' },

  // Fun & Silly Questions (25)
  { text: "If you were a kitchen appliance, which one would you be?", theme: 'Fun & Silly Questions' },
  { text: "What's your most embarrassing 'guilty pleasure' song?", theme: 'Fun & Silly Questions' },
  { text: "If we were in a horror movie, who would survive longer?", theme: 'Fun & Silly Questions' },
  { text: "What's the weirdest food combination you actually enjoy?", theme: 'Fun & Silly Questions' },
  { text: "If you could swap lives with any cartoon character, who would it be?", theme: 'Fun & Silly Questions' },
  { text: "What's the funniest dream you've ever had?", theme: 'Fun & Silly Questions' },
  { text: "If you could have any superpower, but only for 10 minutes a day, what would it be?", theme: 'Fun & Silly Questions' },
  { text: "What's your 'go-to' dance move when nobody is watching?", theme: 'Fun & Silly Questions' },
  { text: "If you were a ghost, who would you haunt first (for fun)?", theme: 'Fun & Silly Questions' },
  { text: "What's the most useless talent you possess?", theme: 'Fun & Silly Questions' },
  { text: "If we could only eat one color of food for a week, which color should we pick?", theme: 'Fun & Silly Questions' },
  { text: "What's your 'wrong' opinion that you will defend to the death?", theme: 'Fun & Silly Questions' },
  { text: "If animals could talk, which one would be the rudest?", theme: 'Fun & Silly Questions' },
  { text: "What's the worst haircut you've ever had?", theme: 'Fun & Silly Questions' },
  { text: "If you were a professional wrestler, what would your entrance theme be?", theme: 'Fun & Silly Questions' },
  { text: "What's the silliest thing you've ever cried about?", theme: 'Fun & Silly Questions' },
  { text: "If you had to change your name to a fruit, which one would you choose?", theme: 'Fun & Silly Questions' },
  { text: "What's the most ridiculous thing you believed as a child?", theme: 'Fun & Silly Questions' },
  { text: "Which fictional world would be the worst to live in?", theme: 'Fun & Silly Questions' },
  { text: "If you were a cat, what would you spend your day doing?", theme: 'Fun & Silly Questions' },
  { text: "What's the most 'dad joke' thing you've ever done?", theme: 'Fun & Silly Questions' },
  { text: "If we were a superhero duo, what would our names be?", theme: 'Fun & Silly Questions' },
  { text: "What's your favorite cheesy pickup line?", theme: 'Fun & Silly Questions' },
  { text: "If you could invent a new holiday, what would it celebrate?", theme: 'Fun & Silly Questions' },
  { text: "What's the weirdest thing you've ever seen in someone else's house?", theme: 'Fun & Silly Questions' },

  // Dream Vacation Plans (25)
  { text: "If we could leave for the airport right now, where would we go?", theme: 'Dream Vacation Plans' },
  { text: "Would you rather stay in a luxury hotel or a cozy cabin in the woods?", theme: 'Dream Vacation Plans' },
  { text: "What's your ultimate 'bucket list' destination?", theme: 'Dream Vacation Plans' },
  { text: "If we lived on a boat for a year, where would we sail?", theme: 'Dream Vacation Plans' },
  { text: "What's the best meal you've ever had while traveling?", theme: 'Dream Vacation Plans' },
  { text: "Sunrise at the beach or sunset in the mountains?", theme: 'Dream Vacation Plans' },
  { text: "If we could travel back in time for one vacation, which era would we visit?", theme: 'Dream Vacation Plans' },
  { text: "What's your favorite travel memory of us?", theme: 'Dream Vacation Plans' },
  { text: "Would you rather go on a 2-week safari or a 2-week European city tour?", theme: 'Dream Vacation Plans' },
  { text: "What's the one thing you always overpack?", theme: 'Dream Vacation Plans' },
  { text: "If we were digital nomads, which city would be our first base?", theme: 'Dream Vacation Plans' },
  { text: "What's the scariest thing you'd be willing to do on vacation (e.g., skydiving)?", theme: 'Dream Vacation Plans' },
  { text: "Describe your perfect 'no-agenda' Sunday in a foreign city.", theme: 'Dream Vacation Plans' },
  { text: "What's a place you've visited that you never want to go back to?", theme: 'Dream Vacation Plans' },
  { text: "If we could visit any fictional planet, which one would it be?", theme: 'Dream Vacation Plans' },
  { text: "Road trip across the country or first-class flight to a private island?", theme: 'Dream Vacation Plans' },
  { text: "What's your favorite souvenir you've ever bought?", theme: 'Dream Vacation Plans' },
  { text: "If we had to move to a different country for one year, where would you choose?", theme: 'Dream Vacation Plans' },
  { text: "What's the most beautiful natural wonder you've ever seen?", theme: 'Dream Vacation Plans' },
  { text: "Camping under the stars or a glamping retreat?", theme: 'Dream Vacation Plans' },
  { text: "What's the one 'tourist trap' you'd actually love to visit?", theme: 'Dream Vacation Plans' },
  { text: "If we could have a second home anywhere in the world, where would it be?", theme: 'Dream Vacation Plans' },
  { text: "What's your favorite way to spend a long flight?", theme: 'Dream Vacation Plans' },
  { text: "Would you rather explore the deep ocean or outer space?", theme: 'Dream Vacation Plans' },
  { text: "What's the most romantic place you can imagine?", theme: 'Dream Vacation Plans' },

  // Relationship Reflections (25)
  { text: "What was your very first impression of me?", theme: 'Relationship Reflections' },
  { text: "When did you first realize you were falling for me?", theme: 'Relationship Reflections' },
  { text: "What is one thing I do that always makes you smile?", theme: 'Relationship Reflections' },
  { text: "What's your favorite memory of our first few dates?", theme: 'Relationship Reflections' },
  { text: "How have we changed as a couple since we first met?", theme: 'Relationship Reflections' },
  { text: "What's a challenge we've overcome that made us stronger?", theme: 'Relationship Reflections' },
  { text: "What's something I've taught you that you're grateful for?", theme: 'Relationship Reflections' },
  { text: "What's your favorite physical feature of mine?", theme: 'Relationship Reflections' },
  { text: "What's a small gesture of mine that means a lot to you?", theme: 'Relationship Reflections' },
  { text: "If we could relive one day from our relationship, which would it be?", theme: 'Relationship Reflections' },
  { text: "What's one goal you'd love for us to achieve together this year?", theme: 'Relationship Reflections' },
  { text: "What's the best compliment I've ever given you?", theme: 'Relationship Reflections' },
  { text: "How do you think we complement each other's personalities?", theme: 'Relationship Reflections' },
  { text: "What's your favorite 'inside joke' that we share?", theme: 'Relationship Reflections' },
  { text: "What's something you admire about how I handle difficult situations?", theme: 'Relationship Reflections' },
  { text: "What is one tradition you'd love for us to start together?", theme: 'Relationship Reflections' },
  { text: "What makes you feel most loved by me?", theme: 'Relationship Reflections' },
  { text: "What's your favorite thing about our daily routine?", theme: 'Relationship Reflections' },
  { text: "What's a song that will always remind you of us?", theme: 'Relationship Reflections' },
  { text: "What's something you're excited for us to do in the future?", theme: 'Relationship Reflections' },
  { text: "What's one thing you're proud of us for as a couple?", theme: 'Relationship Reflections' },
  { text: "How do you think we've grown individually because of this relationship?", theme: 'Relationship Reflections' },
  { text: "What's the most romantic thing we've ever done together?", theme: 'Relationship Reflections' },
  { text: "What's a dream for our relationship that you haven't shared yet?", theme: 'Relationship Reflections' },
  { text: "Why am I your person?", theme: 'Relationship Reflections' }
];

export const INITIAL_QUESTIONS: DateQuestion[] = questions.map((q, i) => ({ ...q, id: i + 1 }));
